[tools]
node = "24.12.0"
pnpm = "latest"

[tasks.init]
description = "Initialize the project"
run = "pnpm install"

[tasks.build]
description = "Build the project"
depends = "init"
run = "pnpm run build"

[tasks.release]
description = "Get jsdelivr CDN URL"
depends = "build"
run = "bash ./scripts/jsdellivr-url.sh"
